import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {    ReactNode } from "react";

export default function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: any;
}) {
  return (
    <html lang={params.locale}>
      <body>{children}</body>
    </html>
  );
}
