name: Nextjs-React-Playground Project Update Common Package

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "serhataydus@hotmail.com"
          git config --global user.name "Serhat Aydus"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Check if Tag Exists
        id: check_tag
        run: echo ::set-output name=TAG_EXISTS::$(npm show <package-name> version | grep -Fx "$(npm version patch)")

      - name: Delete Existing Tag
        if: steps.check_tag.outputs.TAG_EXISTS != ''
        run: git tag -d $(npm version patch)

      - name: Bump Version and Publish
        run: |
          git pull
          git reset --hard HEAD
          git clean -fd
          npm version minor
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
